var stationInfo ={
    finch:{
        name:'Finch Station',
        accessible:true,
        waitingArea:true,
        pickUpDropOff:true,
        washrooms:true,
        bikeRepair:true,
        parking:true,
        presto:true,
        wifi:true,
        connecting:['Brampton Transit', 'Go Transit', 'York Region Transit']
    },
    northYorkCentre:{
        name:'North York Centre Station',
        accessible:true,
        waitingArea:true,
        pickUpDropOff:false,
        washrooms:false,
        bikeRepair:false,
        parking:false,
        presto:true,
        wifi:true,
        cell:false,
        connecting:['none']
    },
    sheppardYonge:{
        name:'Sheppard Yonge Station',
        accessible:true,
        waitingArea:true,
        pickUpDropOff:false,
        washrooms:true,
        bikeRepair:false,
        parking:false,
        presto:true,
        wifi:false,
        cell:false,
        connecting:['Go Transit', 'VIVA', 'York Region Transit']
    },
    yorkMills:{
        name:'York Mills Station',
        accessible:true,
        waitingArea:true,
        pickUpDropOff:true,
        washrooms:false,
        bikeRepair:false,
        parking:false,
        presto:true,
        wifi:false,
        cell:false,
        connecting:['Go Transit']
    },
    lawrence:{
        name:'Lawrence Station',
        accessible:false,
        waitingArea:true,
        pickUpDropOff:false,
        washrooms:false,
        bikeRepair:true,
        parking:false,
        presto:true,
        wifi:false,
        cell:false,
        connecting:['none']
    },
    eglinton:{
        name:'Eglinton Station',
        accessible:true,
        waitingArea:true,
        pickUpDropOff:false,
        washrooms:true,
        bikeRepair:false,
        parking:false,
        presto:true,
        wifi:true,
        connecting:['none']
    },
    davisville:{
        name:'Davisville Station',
        accessible:true,
        waitingArea:true,
        pickUpDropOff:false,
        washrooms:false,
        bikeRepair:true,
        parking:false,
        presto:true,
        wifi:false,
        cell:true,
        connecting:['none']
    },
    stClair:{
        name:'St Clair Station',
        accessible:true,
        waitingArea:true,
        pickUpDropOff:false,
        washrooms:false,
        bikeRepair:true,
        parking:false,
        presto:true,
        wifi:true,
        cell:false,
        connecting:['none']
    },
    summerhill:{
        name:'Summerhill Station',
        accessible:false,
        waitingArea:true,
        pickUpDropOff:false,
        washrooms:false,
        bikeRepair:false,
        parking:false,
        presto:true,
        wifi:true,
        cell:false,
        connecting:['none']
    },
    rosedale:{
        name:'Rosedale Station',
        accessible:false,
        waitingArea:true,
        pickUpDropOff:false,
        washrooms:false,
        bikeRepair:true,
        parking:false,
        presto:true,
        wifi:true,
        cell:false,
        connecting:['none']
    },
    bloorYonge:{
        name:'Bloor-Yonge Station',
        accessible:true,
        waitingArea:true,
        pickUpDropOff:false,
        washrooms:true,
        bikeRepair:false,
        parking:false,
        presto:true,
        wifi:true,
        cell:true,
        connecting:[]
    },
    wellesley:{
        name:'Wellesley Station',
        accessible:true,
        waitingArea:true,
        pickUpDropOff:false,
        washrooms:false,
        bikeRepair:false,
        parking:false,
        presto:true,
        wifi:true,
        cell:true,
        connecting:[]
    },
    college:{
        name:'College Station',
        accessible:false,
        waitingArea:true,
        pickUpDropOff:false,
        washrooms:false,
        bikeRepair:false,
        parking:false,
        presto:true,
        wifi:true,
        cell:true,
        connecting:['none']
    },
    dundas:{
        name:'Dundas Station',
        accessible:true,
        waitingArea:true,
        pickUpDropOff:false,
        washrooms:false,
        bikeRepair:false,
        parking:false,
        presto:true,
        wifi:true,
        cell:true,
        connecting:['none']
    },
    queen:{
        name:'Queen Station',
        accessible:true,
        waitingArea:true,
        pickUpDropOff:false,
        washrooms:false,
        bikeRepair:false,
        parking:false,
        presto:true,
        wifi:true,
        cell:true,
        connecting:['none']
    },
    king:{
        name:'King Station',
        accessible:false,
        waitingArea:true,
        pickUpDropOff:false,
        washrooms:false,
        bikeRepair:false,
        parking:false,
        presto:true,
        wifi:true,
        cell:true,
        connecting:['none']
    },
    union:{
        name:'Union Station',
        accessible:true,
        waitingArea:true,
        pickUpDropOff:false,
        washrooms:false,
        bikeRepair:false,
        parking:false,
        presto:true,
        wifi:true,
        cell:true,
        connecting:['Go Transit', 'Ontario Northland', 'UP Express', 'VIA Rail Canada']
    },
    stAndrew:{
        name:'St Andrew Station',
        accessible:true,
        waitingArea:true,
        pickUpDropOff:false,
        washrooms:false,
        bikeRepair:false,
        parking:false,
        presto:true,
        wifi:true,
        cell:true,
        connecting:['none']   
    },
    osgoode:{
        name:'Osgoode Station',
        accessible:true,
        waitingArea:true,
        pickUpDropOff:false,
        washrooms:false,
        bikeRepair:false,
        parking:false,
        presto:true,
        wifi:true,
        cell:true,
        connecting:['none']
    },
    stPatrick:{
        name:'St Patrick Station',
        accessible:true,
        waitingArea:true,
        pickUpDropOff:false,
        washrooms:false,
        bikeRepair:false,
        parking:false,
        presto:true,
        wifi:true,
        cell:true,
        connecting:['none']
    },
    queensPark:{
        name:"Queen's Park Station",
        accessible:true,
        waitingArea:true,
        pickUpDropOff:false,
        washrooms:false,
        bikeRepair:false,
        parking:false,
        presto:true,
        wifi:true,
        cell:true,
        connecting:['none']
    },
    museum:{
        name:'Museum Station',
        accessible:false,
        waitingArea:true,
        pickUpDropOff:false,
        washrooms:false,
        bikeRepair:false,
        parking:false,
        presto:true,
        wifi:true,
        cell:true,
        connecting:['none']
    },
    stGeorge:{
        name:'St George Station',
        accessible:true,
        waitingArea:true,
        pickUpDropOff:false,
        washrooms:false,
        bikeRepair:true,
        parking:false,
        presto:true,
        wifi:true,
        cell:true,
        connecting:[]
    },
    spadina:{
        name:'Spadina Station',
        accessible:false,
        waitingArea:true,
        pickUpDropOff:false,
        washrooms:false,
        bikeRepair:true,
        parking:false,
        presto:true,
        wifi:true,
        cell:true,
        connecting:['none']
    },
    dupont:{
        name:'Dupont Station',
        accessible:true,
        waitingArea:true,
        pickUpDropOff:false,
        washrooms:false,
        bikeRepair:true,
        parking:false,
        presto:true,
        wifi:true,
        cell:true,
        connecting:['none']
    },
    stClairWest:{
        name:'St Clair West Station',
        accessible:true,
        waitingArea:true,
        pickUpDropOff:false,
        washrooms:false,
        bikeRepair:true,
        parking:false,
        presto:true,
        wifi:true,
        cell:false,
        connecting:['none']
    },
    eglintonWest:{
        name:'Eglinton West Station',
        accessible:true,
        waitingArea:true,
        pickUpDropOff:false,
        washrooms:false,
        bikeRepair:false,
        parking:false,
        presto:true,
        wifi:true,
        cell:false,
        connecting:['none']
    },
    glencairn:{
        name:'Glencairn Station',
        accessible:false,
        waitingArea:true,
        pickUpDropOff:false,
        washrooms:false,
        bikeRepair:false,
        parking:false,
        presto:true,
        wifi:true,
        cell:false,
        connecting:['none']
    },
    lawrenceWest:{
        name:'Lawrence West Station',
        accessible:true,
        waitingArea:true,
        pickUpDropOff:false,
        washrooms:false,
        bikeRepair:true,
        parking:false,
        presto:true,
        wifi:true,
        cell:false,
        connecting:['none']
    },
    yorkdale:{
        name:'Yorkdale Station',
        accessible:true,
        waitingArea:true,
        pickUpDropOff:false,
        washrooms:false,
        bikeRepair:false,
        parking:true,
        presto:true,
        wifi:true,
        cell:false,
        connecting:['Go Transit', 'Ontario Northland', 'York Region Transit']
    }
}

        // accessible:false,
        // waitingArea:false,
        // pickUpDropOff:false,
        // washrooms:false,
        // bikeRepair:false,
        // parking:false,
        // presto:false,
        // wifi:false,
        // cell:false,
        // connecting:[]
